# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ba084c5d2a53dc94b3473b93b22b64be"
name = "country-blocker"
handle = "country-blocker"
application_url = "https://scientific-hungary-eve-damaged.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,write_files,write_metaobject_definitions,write_metaobjects,read_themes"

[auth]
redirect_urls = ["https://scientific-hungary-eve-damaged.trycloudflare.com/auth/callback", "https://scientific-hungary-eve-damaged.trycloudflare.com/auth/shopify/callback", "https://scientific-hungary-eve-damaged.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = false
